defaults:
  - camera: zed2i_512_256
  - renderer: cycles
  - cloth_mesh: default
  - surface: polyhaven
  - distractors: default
  - annotator: default
  - _self_

cloth_type: LEGO
id: 5
relative_dataset_path: synthetic_images/LEGO-battery/02-better-obj

cloth_mesh:
  mesh_path: flat_meshes/LEGO-battery
  solidify: False
  subdivide: False

cloth_material:
  _target_: synthetic_cloth_data.synthetic_images.scene_builder.cloth_material.PolyhavenMaterialConfig

camera:
  minimal_camera_height: 0.1
  max_sphere_radius: 0.4