defaults:
  - camera: zed2i_512_256
  - renderer: cycles
  - cloth_mesh: default
  - cloth_material: hsv
  - surface: hsv
  - distractors: default
  - _self_

cloth_type: TOWEL
id: 5
relative_dataset_path: synthetic_images/TOWEL/06-smaller

cloth_mesh:
  mesh_path: deformed_meshes/TOWEL/03-smaller
