defaults:
  - camera: zed2i_512_256
  - cloth_mesh: default
  - _self_


cloth_type: TSHIRT
id: 5
relative_dataset_path: synthetic_images/TSHIRT/00

cloth_mesh:
  mesh_path: deformed_meshes/TSHIRT/pyflex/cloth3d
