defaults:
  - camera: zed2i_512_256
  - renderer: cycles
  - cloth_mesh: default
  - cloth_material: tshirt
  - surface: polyhaven
  - distractors: default
  - annotator: default
  - _self_


cloth_type: TSHIRT
id: 2
relative_dataset_path: synthetic_images/TSHIRT/dev

cloth_mesh:
  mesh_path: deformed_meshes/TSHIRT/02-cloth3d-flat-5K
