name: Pytest

on:
  pull_request:
  push:
    branches: [main,ci-dev]

jobs:
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: pytest
        shell: bash -l {0}
        run: |
          pytest test/